[package]
name = "lesson-002"
version = "0.1.0"
edition = "2024"

[dependencies]
leptos = { version = "0.8.11", features = ["csr"] }
wasm-bindgen-test = "0.3.50"
wasm-bindgen = "0.2.100"
web-sys = "0.3.77"

[dev-dependencies]
wasm-bindgen-test = "0.3.50"
wasm-bindgen = "0.2.100"
web-sys = "0.3.77"