[package]
name = "lesson-012"
version = "0.1.0"
edition = "2024"

[dependencies]

leptos = { version = "0.8.2", default-features = false, "features" = ["csr"] }
reactive_stores = { version = "0.2.2" }

[features]
csr = []